# Generated by Django 4.2.11 on 2024-05-18 11:41

import attachments.models
import charidfield.fields
from django.db import migrations, models
import ulid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    charidfield.fields.CharIDField(
                        default=ulid.ULID,
                        editable=False,
                        max_length=26,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno dne")),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Upraveno dne")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Poznámka")),
                ("tag", models.CharField(blank=True, max_length=255, verbose_name="Označení souboru")),
                ("file_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Název souboru")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=attachments.models.attachment_directory_path,
                        verbose_name="Soubor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
        migrations.CreateModel(
            name="DefaultAttachment",
            fields=[
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    charidfield.fields.CharIDField(
                        default=ulid.ULID,
                        editable=False,
                        max_length=26,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno dne")),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Upraveno dne")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Poznámka")),
                ("tag", models.CharField(blank=True, max_length=255, verbose_name="Označení souboru")),
                ("file_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Název souboru")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=attachments.models.default_attachment_directory_path,
                        verbose_name="Soubor",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("proposal", "Proposal"), ("contract", "Contract"), ("protocol", "Protocol")],
                        default="contract",
                        max_length=255,
                        verbose_name="Typ dokumentu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Default Attachment",
                "verbose_name_plural": "Default Attachments",
            },
        ),
    ]
