# Generated by Django 4.2.11 on 2024-03-25 15:31

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno dne')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno dne')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('tag', models.CharField(blank=True, max_length=255, verbose_name='Označení souboru')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Název souboru')),
                ('file', models.FileField(blank=True, null=True, upload_to=attachments.models.attachment_directory_path, verbose_name='soubor')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='DefaultAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno dne')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno dne')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('tag', models.CharField(blank=True, max_length=255, verbose_name='Označení souboru')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Název souboru')),
                ('file', models.FileField(blank=True, null=True, upload_to=attachments.models.default_attachment_directory_path, verbose_name='soubor')),
            ],
            options={
                'verbose_name': 'Default Attachment',
                'verbose_name_plural': 'Default Attachments',
            },
        ),
    ]
