# Generated by Django 4.2.11 on 2024-03-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('attachments', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultattachment',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='default_attachments', to='clients.client', verbose_name='klient'),
        ),
        migrations.AddField(
            model_name='defaultattachment',
            name='contract_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='base.contractsubject', verbose_name='Předmět smlouvy'),
        ),
        migrations.AddField(
            model_name='defaultattachment',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='base.contracttype', verbose_name='Typ smlouvy'),
        ),
        migrations.AddField(
            model_name='defaultattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AddField(
            model_name='defaultattachment',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Upravil'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='clients.client', verbose_name='klient'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Upravil'),
        ),
    ]
