# Generated by Django 4.1.3 on 2023-03-07 10:55

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_attachment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=attachments.models.attachment_directory_path),
        ),
    ]
