# Generated by Django 4.2.11 on 2024-03-26 15:23

import attachments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('attachments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultattachment',
            name='document_type',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('contract', 'Contract'), ('protocol', 'Protocol')], default='contract', max_length=255, verbose_name='Typ dokumentu'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='clients.client', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=attachments.models.attachment_directory_path, verbose_name='Soubor'),
        ),
        migrations.AlterField(
            model_name='defaultattachment',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='default_attachments', to='clients.client', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='defaultattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=attachments.models.default_attachment_directory_path, verbose_name='Soubor'),
        ),
    ]
