version: '3.8'
services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    expose:
      - "8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:8000"
    depends_on:
      - django_gunicorn

  db:
    image: postgres:14.6
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=kontraktor
      - POSTGRES_PASSWORD=gtdkjap58439kjfaLKJL
      - POSTGRES_DB=kontraktor

volumes:
  static:
  pg_data:
