#version: "3.7"
services:
#  web:
#    restart: always
#    build:
#      context: .
#    expose:
#      - "8000"
#    links:
#      - postgres:postgres
#    volumes:
#      - web-static:/static
#    env_file: .env

  web:
    build:
      context: "."
      target: "app"
      args:
        - "UID=1000"
        - "GID=1000"
    depends_on:
      - "postgres"
    env_file:
      - ".env"
    restart: "always"
    stop_grace_period: "3s"
    tty: true
    volumes:
      - web-static:/static
    deploy:
      resources:
        limits:
          cpus: "0"
          memory: "0"
    ports:
      - "8000:8000"
    profiles: [ "web" ]

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  web-static:
  pgdata:


