version: '3'

services:
  web:
    restart: always
    build:
      context: .
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - web-static:/static
    env_file: .env
    profiles: ["web"]

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/static
    links:
      - web:web
    profiles: ["nginx"]

  postgres:
    restart: always
    image: "postgres:15.3-bullseye"
    profiles: [ "postgres" ]
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  web-static:
  pgdata:
