# Generated by Django 4.1.3 on 2022-12-16 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Číslo smlouvy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořena dne')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Upravena dne')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Podepsána dne')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Upravil')),
                ('proposal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.proposal', verbose_name='Nabídka')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, choices=[('1', 'Základní ustanovení'), ('2', 'Záruka za jakost a vady díla'), ('3', 'Sankce'), ('4', 'Pokyny pro užívání a údržbu dodávaných výrobků'), ('5', 'Montážní a skladovací podmínky'), ('6', 'Reklamační řád'), ('7', 'Volný oddíl'), ('8', 'Volný oddíl'), ('9', 'Závěrečná ustanovení')], max_length=100, null=True, verbose_name='Oddíl')),
                ('priority', models.IntegerField()),
                ('text', models.TextField(blank=True, max_length=10000, null=True)),
                ('essential', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('contract', models.ManyToManyField(related_name='contract_cores', to='contracts.contract')),
                ('contract_type', models.ManyToManyField(related_name='contract_cores', to='proposals.contracttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_core_created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_core_edited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Core',
                'verbose_name_plural': 'Contract Cores',
                'ordering': ['priority'],
                'unique_together': {('priority', 'text')},
            },
        ),
    ]
