# Generated by Django 4.1.3 on 2022-11-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='subject',
            field=models.CharField(blank=True, choices=[('DVERE', 'pouze dveře'), ('PODLAHA', 'pouze podlaha'), ('DVERE_PODLAHA', 'dveře i podlaha'), ('ZBOZI', 'zboží')], max_length=100, null=True),
        ),
    ]
