# Generated by Django 4.1.3 on 2022-11-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_contract_party_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
