# Generated by Django 4.1.3 on 2022-11-21 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_contract_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='corporation',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContractCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('type_usage', models.CharField(blank=True, choices=[('KOUPE', 'koupě'), ('DILO', 'dílo')], max_length=8, null=True)),
                ('text', models.TextField(blank=True, max_length=10000, null=True)),
                ('essential', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=4, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_cores', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_core_created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_core_edited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
