# Generated by Django 4.1.3 on 2022-11-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_attachment_contract_alter_contract_corporation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractcore',
            name='contract',
        ),
        migrations.AddField(
            model_name='contractcore',
            name='contract',
            field=models.ManyToManyField(blank=True, null=True, related_name='contract_cores', to='contracts.contract'),
        ),
    ]
