# Generated by Django 4.1.3 on 2022-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_remove_contractcore_contract_contractcore_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcore',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='contract',
            field=models.ManyToManyField(related_name='contract_cores', to='contracts.contract'),
        ),
    ]
