# Generated by Django 4.1.3 on 2022-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contractcore_note_alter_contractcore_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KOUPE', 'koupě'), ('DILO', 'dílo')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='type',
        ),
        migrations.RemoveField(
            model_name='contractcore',
            name='type_usage',
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='contract',
            field=models.ManyToManyField(choices=[('KOUPE', 'koupě'), ('DILO', 'dílo')], related_name='contract_cores', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ManyToManyField(choices=[('KOUPE', 'koupě'), ('DILO', 'dílo')], related_name='contracts', to='contracts.contracttype'),
        ),
        migrations.AddField(
            model_name='contractcore',
            name='contract_type',
            field=models.ManyToManyField(related_name='contract_cores', to='contracts.contracttype'),
        ),
    ]
