# Generated by Django 4.1.3 on 2022-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.ManyToManyField(related_name='contracts', to='contracts.contracttype', verbose_name='Typ smlouvy'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fulfillment_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
