# Generated by Django 4.1.3 on 2022-11-23 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0010_contracttype_name_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Adresa bydliště'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Číslo smlouvy'),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
        migrations.AlterField(
            model_name='contract',
            name='corporation',
            field=models.BooleanField(default=False, verbose_name='Korporace'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořena dne'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Upravena dne'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Upravil'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mailová adresa'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fulfillment_at',
            field=models.DateField(blank=True, null=True, verbose_name='Čas plnění'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fulfillment_place',
            field=models.CharField(max_length=1000, verbose_name='Místo plnění'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Datum narození nebo IČ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefonní číslo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Podepsána dne'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='subject',
            field=models.CharField(blank=True, choices=[('DVERE', 'pouze dveře'), ('PODLAHA', 'pouze podlaha'), ('DVERE_PODLAHA', 'dveře i podlaha'), ('ZBOZI', 'zboží')], max_length=100, null=True, verbose_name='Předmět smlouvy'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.contracttype', verbose_name='Typ smlouvy'),
        ),
    ]
