# Generated by Django 4.1.3 on 2022-11-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_remove_contract_corporation_contract_consumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='consumer',
            field=models.BooleanField(default=True, verbose_name='Spotřebitel (fyzická osoba)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Datum narození nebo IČ'),
        ),
    ]
