# Generated by Django 4.1.3 on 2022-11-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_contract_consumer_alter_contract_id_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractcore',
            options={'verbose_name': 'Contract Core', 'verbose_name_plural': 'Contract Cores'},
        ),
        migrations.AddField(
            model_name='contractcore',
            name='section',
            field=models.CharField(blank=True, choices=[('1', 'Základní ustanovení'), ('2', 'Záruka za jakost a vady díla'), ('3', 'Sankce'), ('4', 'Pokyny pro užívání a údržbu dodávaných výrobků'), ('5', 'Montážní a skladovací podmínky'), ('6', 'Reklamační řád'), ('9', 'Závěrečná ustanovení')], max_length=100, null=True, verbose_name='Oddíl'),
        ),
        migrations.AlterUniqueTogether(
            name='contractcore',
            unique_together={('priority', 'text')},
        ),
    ]
