# Generated by Django 4.1.3 on 2022-11-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_contractcore_options_contractcore_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='contractcore',
            options={'ordering': ['priority'], 'verbose_name': 'Contract Core', 'verbose_name_plural': 'Contract Cores'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='section',
            field=models.CharField(blank=True, choices=[('1', 'Základní ustanovení'), ('2', 'Záruka za jakost a vady díla'), ('3', 'Sankce'), ('4', 'Pokyny pro užívání a údržbu dodávaných výrobků'), ('5', 'Montážní a skladovací podmínky'), ('6', 'Reklamační řád'), ('7', 'Volný oddíl'), ('8', 'Volný oddíl'), ('9', 'Závěrečná ustanovení')], max_length=100, null=True, verbose_name='Oddíl'),
        ),
    ]
