# Generated by Django 4.1.3 on 2022-11-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_alter_attachment_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
