# Generated by Django 4.2.8 on 2023-12-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonní číslo'),
        ),
    ]
