# Generated by Django 4.1.3 on 2022-12-19 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sign_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Kód pro potvrzení'),
        ),
    ]
