# Generated by Django 4.1.3 on 2022-12-19 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_sign_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sign_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Kód pro potvrzení'),
        ),
    ]
