# Generated by Django 4.1.3 on 2023-04-13 12:42

import clients.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('clients', '0003_alter_client_sign_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořen')),
                ('file', models.ImageField(blank=True, null=True, upload_to=clients.models.signature_directory_path, verbose_name='Obrázek podpisu')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='clients.client', verbose_name='Klient')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
            },
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['content_type', 'object_id'], name='clients_sig_content_16121b_idx'),
        ),
    ]
