# Generated by Django 4.1.3 on 2023-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_signature_signature_clients_sig_content_16121b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='ip',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='IP adresa clienta'),
        ),
    ]
