# Generated by Django 4.1.3 on 2022-12-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jméno')),
                ('id_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Datum narození nebo IČ')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Adresa bydliště nebo sídla')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mailová adresa')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefonní číslo')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Poznámka')),
                ('consumer', models.BooleanField(default=True, verbose_name='Spotřebitel (fyzická osoba)')),
            ],
        ),
    ]
