# Generated by Django 4.2.8 on 2023-12-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('ks', 'Ks'), ('kg', 'Kg'), ('l', 'Liters'), ('mb', 'Cubic Meters'), ('m2', 'Square Meters'), ('hod', 'Hours')], default='ks', max_length=5, null=True, verbose_name='jednotka'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('ks', 'Ks'), ('kg', 'Kg'), ('l', 'Liters'), ('mb', 'Cubic Meters'), ('m2', 'Square Meters'), ('hod', 'Hours')], default='ks', max_length=5, null=True, verbose_name='jednotka'),
        ),
    ]
