# Generated by Django 4.1.3 on 2022-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='fulfillment_at',
            field=models.DateField(blank=True, null=True, verbose_name='Termín plnění'),
        ),
    ]
