# Generated by Django 4.1.3 on 2023-03-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_proposal_signed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='celková cena'),
        ),
        migrations.AlterField(
            model_name='item',
            name='production_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='nákladová cena za jednotku'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cena ze jednotku'),
        ),
    ]
