# Generated by Django 4.1.3 on 2023-03-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_item_total_sale_price_alter_item_production_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='proposals.contractsubject', verbose_name='Předmět nabídky'),
        ),
    ]
