# Generated by Django 4.1.3 on 2023-03-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_contractsubject_alter_proposal_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sale_price',
            new_name='price_per_unit',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='total_sale_price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='price',
        ),
        migrations.AddField(
            model_name='contracttype',
            name='vat',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='proposal',
            name='price_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Cena s DPH'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='price_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Cena bez DPH'),
        ),
    ]
