# Generated by Django 4.1.3 on 2023-01-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operator', 'verbose_name_plural': 'Operators'},
        ),
        migrations.AddField(
            model_name='operator',
            name='web',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link operátora'),
        ),
    ]
