# Generated by Django 4.2.11 on 2024-03-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='proposal_validity',
            field=models.IntegerField(default=14),
        ),
    ]
