# Generated by Django 4.1.3 on 2023-03-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_alter_operator_options_operator_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='operator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon'),
        ),
    ]
