# Generated by Django 4.1.3 on 2022-12-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='pořadí')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='název')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='popis')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cena')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='sleva')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='množství')),
                ('production_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='výrobní termín')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['priority'],
            },
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
    ]
