# Generated by Django 4.1.3 on 2022-12-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_item_alter_proposal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proposals.proposal', verbose_name='nabídka'),
        ),
        migrations.CreateModel(
            name='UploadedProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(blank=True, max_length=3, null=True, verbose_name='pořadí')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='soubor')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='název souboru')),
                ('proposal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded', to='proposals.proposal', verbose_name='nabídka')),
            ],
            options={
                'verbose_name': 'UploadedProposal',
                'verbose_name_plural': 'UploadedProposals',
                'ordering': ['priority'],
            },
        ),
    ]
