# Generated by Django 4.1.3 on 2023-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_proposal_fulfillment_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='signed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Potvrzena dne'),
        ),
    ]
