# Generated by Django 4.1.3 on 2022-12-09 12:33

from django.db import migrations, models
import django.db.models.deletion
import proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
        ('proposals', '0003_item_proposal_uploadedproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='clients.client', verbose_name='klient'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Potvrzena dne'),
        ),
        migrations.AlterField(
            model_name='uploadedproposal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=proposals.models.uploaded_proposal_directory_path, verbose_name='soubor'),
        ),
    ]
