# Generated by Django 4.1.3 on 2022-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_client_alter_proposal_signed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedproposal',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Nahráno dne'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='fulfillment_place',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Místo plnění'),
        ),
    ]
