# Generated by Django 4.1.3 on 2022-12-13 15:13

from django.db import migrations, models
import proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_uploadedproposal_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='production_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='discount',
            new_name='sale_discount',
        ),
        migrations.AddField(
            model_name='item',
            name='production_data',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='výrobní data'),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='uploadedproposal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=proposals.models.uploaded_proposal_directory_path, verbose_name='Podkladová nabídka'),
        ),
    ]
