# Generated by Django 4.1.3 on 2022-12-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_alter_uploadedproposal_options_alter_proposal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cena'),
        ),
    ]
