# Generated by Django 4.1.3 on 2022-12-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_alter_proposal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Cena'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='výše')),
                ('part', models.IntegerField(verbose_name='část z celku')),
                ('due', models.CharField(choices=[('after_sign', 'po podpisu smlouvy'), ('after_delivery', 'před dodáním'), ('before_delivery', 'po dodání'), ('after_completion', 'před dokončením'), ('before_completion', 'po dokončení')], default=('after_sign', 'po podpisu smlouvy'), max_length=100, verbose_name='splatnost')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='proposals.proposal', verbose_name='nabídka')),
            ],
        ),
    ]
