# Generated by Django 4.1.3 on 2022-12-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_alter_proposal_price_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due',
            field=models.CharField(choices=[('AS', 'po podpisu smlouvy'), ('AD', 'po dodáním'), ('BD', 'před dodání'), ('AC', 'po dokončení'), ('BC', 'před dokončením')], default='AS', max_length=100, verbose_name='splatnost'),
        ),
    ]
