# Generated by Django 4.2.11 on 2024-05-18 11:41

import charidfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ulid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    charidfield.fields.CharIDField(
                        default=ulid.ULID,
                        editable=False,
                        max_length=26,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno dne")),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Upraveno dne")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Poznámka")),
                ("priority", models.IntegerField(verbose_name="Číslo oddílu")),
                ("name", models.CharField(blank=True, max_length=200, verbose_name="Název oddílu")),
                (
                    "contract_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="base.contractsubject",
                        verbose_name="Předmět smlouvy",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="base.contracttype",
                        verbose_name="Typ smlouvy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_edited_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upravil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document section",
                "verbose_name_plural": "Document sections",
            },
        ),
        migrations.CreateModel(
            name="DocumentParagraph",
            fields=[
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    charidfield.fields.CharIDField(
                        default=ulid.ULID,
                        editable=False,
                        max_length=26,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno dne")),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Upraveno dne")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Poznámka")),
                (
                    "document_type",
                    models.CharField(
                        choices=[("proposal", "Proposal"), ("contract", "Contract"), ("protocol", "Protocol")],
                        default="contract",
                        max_length=255,
                        verbose_name="Typ dokumentu",
                    ),
                ),
                ("priority", models.IntegerField(verbose_name="Číslo ustanovení")),
                ("text", models.TextField(blank=True, max_length=10000, null=True, verbose_name="Text ustanovení")),
                ("essential", models.BooleanField(default=False, verbose_name="Nepominutelné")),
                ("editable", models.BooleanField(default=True, verbose_name="Upravitelné")),
                ("default", models.BooleanField(default=True, verbose_name="Původní")),
                ("parent_id", models.CharField(blank=True, null=True, verbose_name="ID původního ustanovení")),
                (
                    "contract_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="base.contractsubject",
                        verbose_name="Předmět smlouvy",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="base.contracttype",
                        verbose_name="Typ smlouvy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "document_section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_paragraphs",
                        to="documents.documentsection",
                        verbose_name="Oddíl",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_edited_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upravil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Paragraph",
                "verbose_name_plural": "Document Paragraphs",
                "ordering": ["priority"],
                "unique_together": {("priority", "text", "document_section")},
            },
        ),
    ]
