# Generated by Django 4.2.11 on 2024-03-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno dne')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno dne')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('priority', models.IntegerField(verbose_name='Číslo oddílu')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Název oddílu')),
                ('contract_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='base.contractsubject', verbose_name='Předmět smlouvy')),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='base.contracttype', verbose_name='Typ smlouvy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Upravil')),
            ],
            options={
                'verbose_name': 'Document section',
                'verbose_name_plural': 'Document sections',
            },
        ),
        migrations.CreateModel(
            name='DocumentParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno dne')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraveno dne')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('document_type', models.CharField(choices=[('proposal', 'Proposal'), ('contract', 'Contract'), ('protocol', 'Protocol')], default='contract', max_length=255, verbose_name='Typ dokumentu')),
                ('priority', models.IntegerField(verbose_name='Číslo ustanovení')),
                ('text', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Text ustanovení')),
                ('essential', models.BooleanField(default=False, verbose_name='Nepominutelné')),
                ('editable', models.BooleanField(default=True, verbose_name='Upravitelné')),
                ('default', models.BooleanField(default=True, verbose_name='Původní')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='ID původního ustanovení')),
                ('contract_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='base.contractsubject', verbose_name='Předmět smlouvy')),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='base.contracttype', verbose_name='Typ smlouvy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('document_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_paragraphs', to='documents.documentsection', verbose_name='Oddíl')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Upravil')),
            ],
            options={
                'verbose_name': 'Document Paragraph',
                'verbose_name_plural': 'Document Paragraphs',
                'ordering': ['priority'],
                'unique_together': {('priority', 'text', 'document_section')},
            },
        ),
    ]
