# Generated by Django 4.1.3 on 2022-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='purpose',
            field=models.CharField(blank=True, choices=[('intern', 'intern'), ('proposal', 'proposal'), ('contract', 'contract'), ('both', 'both')], max_length=10, null=True),
        ),
    ]
