# Generated by Django 4.1.3 on 2022-12-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_remove_attachment_contract_attachment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='add_to_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='add_to_proposal',
            field=models.BooleanField(default=False),
        ),
    ]
