# Generated by Django 4.1.3 on 2022-12-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_rename_name_attachment_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
