# Generated by Django 4.1.3 on 2022-12-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_attachment_tag_alter_attachment_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='add_to_contract',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='add_to_proposal',
        ),
        migrations.AddField(
            model_name='attachment',
            name='purpose',
            field=models.CharField(blank=True, choices=[('intern', 'intern'), ('proposal', 'proposal'), ('contract', 'contract'), ('both', 'audbothio')], max_length=10, null=True),
        ),
    ]
