# Generated by Django 4.2.11 on 2024-05-18 11:41

import charidfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ulid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("documents", "0001_initial"),
        ("attachments", "0002_initial"),
        ("base", "0001_initial"),
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    charidfield.fields.CharIDField(
                        default=ulid.ULID,
                        editable=False,
                        max_length=26,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno dne")),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Upraveno dne")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Poznámka")),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Číslo dokumentu"),
                ),
                ("signed_at", models.DateField(blank=True, null=True, verbose_name="Potvrzen dne")),
                (
                    "attachments",
                    models.ManyToManyField(
                        related_name="%(class)ss", to="attachments.attachment", verbose_name="Přílohy"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="clients.client",
                        verbose_name="klient",
                    ),
                ),
                (
                    "contract_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="base.contractsubject",
                        verbose_name="Předmět smlouvy",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="base.contracttype",
                        verbose_name="Typ smlouvy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "default_attachments",
                    models.ManyToManyField(
                        related_name="%(class)ss", to="attachments.defaultattachment", verbose_name="Automatické přílohy"
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_edited_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upravil",
                    ),
                ),
                (
                    "paragraphs",
                    models.ManyToManyField(
                        related_name="%(class)ss", to="documents.documentparagraph", verbose_name="Ustanovení"
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposals.proposal",
                        verbose_name="Nabídka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    charidfield.fields.CharIDField(
                        default=ulid.ULID,
                        editable=False,
                        max_length=26,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno dne")),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Upraveno dne")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Poznámka")),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Číslo dokumentu"),
                ),
                ("signed_at", models.DateField(blank=True, null=True, verbose_name="Potvrzen dne")),
                ("priority", models.IntegerField(default=1, verbose_name="Číslo protokolu")),
                (
                    "attachments",
                    models.ManyToManyField(
                        related_name="%(class)ss", to="attachments.attachment", verbose_name="Přílohy"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="clients.client",
                        verbose_name="klient",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="contracts.contract",
                        verbose_name="Smlouva",
                    ),
                ),
                (
                    "contract_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="base.contractsubject",
                        verbose_name="Předmět smlouvy",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="base.contracttype",
                        verbose_name="Typ smlouvy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "default_attachments",
                    models.ManyToManyField(
                        related_name="%(class)ss", to="attachments.defaultattachment", verbose_name="Automatické přílohy"
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_edited_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upravil",
                    ),
                ),
                (
                    "paragraphs",
                    models.ManyToManyField(
                        related_name="%(class)ss", to="documents.documentparagraph", verbose_name="Ustanovení"
                    ),
                ),
            ],
            options={
                "verbose_name": "Handover Protocol",
                "verbose_name_plural": "Handover Protocols",
            },
        ),
        migrations.CreateModel(
            name="ProtocolItem",
            fields=[
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    charidfield.fields.CharIDField(
                        default=ulid.ULID,
                        editable=False,
                        max_length=26,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno dne")),
                ("edited_at", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Upraveno dne")),
                ("note", models.TextField(blank=True, null=True, verbose_name="Poznámka")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Upřesnění")),
                (
                    "status",
                    models.CharField(
                        choices=[("yes", "Předáno"), ("with_note", "Předáno s výhradou"), ("no", "Nepředáno")],
                        max_length=20,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vytvořil",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_edited_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Upravil",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="proposals.item",
                        verbose_name="Položka",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="contracts.protocol",
                        verbose_name="Předávací protokol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handover protocol item",
                "verbose_name_plural": "Handover protocol items",
            },
        ),
    ]
