# Generated by Django 4.1.3 on 2023-11-09 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Číslo smlouvy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořena dne')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Upravena dne')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Podepsána dne')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Upravil')),
                ('proposal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.proposal', verbose_name='Nabídka')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořen dne')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraven dne')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Podepsán dne')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Poznámka k protokolu')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='clients.client', verbose_name='Klient')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='contracts.contract', verbose_name='Smlouva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Upravil')),
            ],
            options={
                'verbose_name': 'Handover Protocol',
                'verbose_name_plural': 'Handover Protocols',
            },
        ),
        migrations.CreateModel(
            name='ProtocolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Upřesnění')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('status', models.CharField(choices=[('yes', 'Předáno'), ('with_note', 'Předáno s výhradou'), ('no', 'Nepředáno')], max_length=20, verbose_name='Stav')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Vytvořen dne')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_item_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='proposals.item', verbose_name='Položka')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.protocol', verbose_name='Předávací protokol')),
            ],
            options={
                'verbose_name': 'Handover protocol item',
                'verbose_name_plural': 'Handover protocol items',
            },
        ),
        migrations.CreateModel(
            name='ContractSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Číslo oddílu')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Název oddílu')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_sections', to='proposals.contracttype', verbose_name='Typ smlouvy')),
            ],
            options={
                'verbose_name': 'Contract section',
                'verbose_name_plural': 'Contract sections',
            },
        ),
        migrations.CreateModel(
            name='ContractCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Číslo ustanovení')),
                ('text', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Text ustanovení')),
                ('essential', models.BooleanField(default=False, verbose_name='Nepominutelné')),
                ('editable', models.BooleanField(default=True, verbose_name='Upravitelné')),
                ('default', models.BooleanField(default=True, verbose_name='Původní')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='ID původního ustanovení')),
                ('note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Poznámka')),
                ('contract', models.ManyToManyField(related_name='contract_cores', to='contracts.contract', verbose_name='Smlouva')),
                ('contract_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_cores', to='contracts.contractsection', verbose_name='Oddíl')),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.contracttype', verbose_name='Typ smlouvy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_core_created_by', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_core_edited_by', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_cores', to='proposals.contractsubject', verbose_name='Předmět smlouvy')),
            ],
            options={
                'verbose_name': 'Contract Core',
                'verbose_name_plural': 'Contract Cores',
                'ordering': ['priority'],
                'unique_together': {('priority', 'text', 'contract_section')},
            },
        ),
    ]
