# Generated by Django 4.1.3 on 2023-04-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_rename_sale_price_item_price_per_unit_and_more'),
        ('contracts', '0002_alter_contract_signed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcore',
            name='contract',
            field=models.ManyToManyField(related_name='contract_cores', to='contracts.contract', verbose_name='Smlouva'),
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='default',
            field=models.BooleanField(default=True, verbose_name='Původní'),
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='editable',
            field=models.BooleanField(default=True, verbose_name='Upravitelné'),
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='essential',
            field=models.BooleanField(default=False, verbose_name='Nepominutelné'),
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID původního ustanovení'),
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='priority',
            field=models.IntegerField(verbose_name='Číslo ustanovení'),
        ),
        migrations.AlterField(
            model_name='contractcore',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Text ustanovení'),
        ),
        migrations.CreateModel(
            name='ContractSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Číslo oddílu')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Název oddílu')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_sections', to='proposals.contracttype', verbose_name='Typ smlouvy')),
            ],
            options={
                'verbose_name': 'Contract section',
                'verbose_name_plural': 'Contract sections',
            },
        ),
        migrations.AddField(
            model_name='contractcore',
            name='contract_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_cores', to='contracts.contractsection', verbose_name='Oddíl'),
        ),
    ]
