# Generated by Django 4.1.3 on 2023-04-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contractcore_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractcore',
            name='section',
        ),
    ]
