# Generated by Django 4.1.3 on 2023-06-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_rename_sale_price_item_price_per_unit_and_more'),
        ('clients', '0005_signature_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_remove_contractcore_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořen dne')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Upraven dne')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Podepsán dne')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Poznámka k protokolu')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='clients.client', verbose_name='Klient')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='contracts.contract', verbose_name='Smlouva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_edited_by', to=settings.AUTH_USER_MODEL, verbose_name='Upravil')),
            ],
            options={
                'verbose_name': 'Handover Protocol',
                'verbose_name_plural': 'Handover Protocols',
            },
        ),
        migrations.CreateModel(
            name='ProtocolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('yes', 'Předáno'), ('with_note', 'Předáno s výhradou'), ('no', 'Nepředáno')], max_length=20, verbose_name='Stav')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Vytvořen dne')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_item_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='proposals.item', verbose_name='Položka')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.protocol', verbose_name='Předávací protokol')),
            ],
            options={
                'verbose_name': 'Handover protocol item',
                'verbose_name_plural': 'Handover protocol items',
                'unique_together': {('item', 'created_at')},
            },
        ),
    ]
