# Generated by Django 4.1.3 on 2023-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_protocol_protocolitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='protocolitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='protocolitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Upřesnění'),
        ),
        migrations.AlterField(
            model_name='protocolitem',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
    ]
