# Generated by Django 4.1.3 on 2023-11-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000, verbose_name='Předmět zprávy')),
                ('message', models.CharField(max_length=1000, verbose_name='Obsah zprávy')),
                ('recipients', models.CharField(max_length=1000, verbose_name='Adresát')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořen')),
                ('sent', models.BooleanField(default=False, verbose_name='Odeslán')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='clients.client', verbose_name='Klient')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-maily',
            },
        ),
    ]
