# Generated by Django 4.1.3 on 2023-11-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='recipients',
        ),
        migrations.AddField(
            model_name='mail',
            name='sender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Odesílatel'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.TextField(verbose_name='Obsah zprávy'),
        ),
    ]
