# Generated by Django 4.2.8 on 2024-01-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0002_remove_mail_recipients_mail_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='receiver',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresát'),
        ),
    ]
