# Generated by Django 4.2.9 on 2024-02-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0003_mail_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='documents',
            field=models.TextField(blank=True, null=True, verbose_name='Týká se dokumentů'),
        ),
        migrations.AddField(
            model_name='mail',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
    ]
