# Generated by Django 4.2.9 on 2024-02-19 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailing', '0004_mail_documents_mail_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='sent',
        ),
        migrations.AddField(
            model_name='mail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil'),
        ),
        migrations.AddField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('odeslán', 'Sent'), ('vytvořen', 'Created'), ('nepodařilo se odeslat', 'Failed')], default='vytvořen', max_length=30, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořen dne'),
        ),
    ]
