name: Deploy to servers

on: workflow_dispatch

jobs:
  deploy-on-shi:
    name: Deploy on devel server
    runs-on: ubuntu-latest
    steps:
      - name: Check codebase
        uses: actions/checkout@v4

      - name: Deploy to devel server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SHI_HOST }}
          username: ${{ vars.DEMO_USER }}
          password: ${{ secrets.DEMO_PASSWORD }}
          script: |
            cd kontraktor/
            docker compose down
            docker compose pull
            docker compose up -d
